const listings = [
    {
        "Address": "11531 38th Ave NE",
        "Subaddress": "Seattle, WA 98125",
        "Photos": ["/static/images/PropertyPhotos/11531/1.jpg",],
        "MLS": "2150028",
        "Beds": 5,
        "Baths": 3.25,
        "SqFt": "2,727 SqFt",
        "MarketingRemarks": "This 5 bed + 3.25 bath oasis allows for flexibility & space to create the home atmosphere you desire. Grand open-concept great room spills out onto a private deck & backyard to create the perfect indoor/outdoor experience. Chefs will enjoy a kitchen featuring stainless steel appliances, stylish finishes & oversized walk-in pantry. Unwind in the deluxe primary suite with a 5-piece bath & private patio that gives home a spa-like experience. Utilize the spacious additional bedrooms for guests, recreational space, work from home office & more! With giant walk-in closets throughout & dedicated laundry room, embrace the perfect blend of comfort & convenience. This home also includes EV ready parking.",
        "Price": "$1,199,950",
        "Media": "https://login.focusedmediacollective.com/11531-38th-Ave-NE",
        "Header": "/static/images/PropertyPhotos/11531_header.png",

    },
    {
        "Address": "8514 1st Ave NE",
        "Subaddress": "Seattle, WA 98115",
        "Photos": ["/static/images/PropertyPhotos/8514/1.jpg",],
        "MLS": "2164527",
        "Beds": 5,
        "Baths": 3.25,
        "SqFt": "2,558 SqFt",
        "MarketingRemarks": "New construction home with a luxurious owner's level, spacious open living & dining area, & four functional additional bedrooms. On the massive owner's level, you’ll find a deluxe five-piece bathroom with heated flooring, expansive walk-in closet & a private covered balcony. Explore the chef's dream kitchen boasting top-of-the-line appliances, modern finishes & a jumbo-sized pantry. Generous living room flows onto private patio, perfect for summer days. Finally, grab some snacks & find your way to the bonus room, prepped for a future wet bar - with potential to convert to a rental. With two private parking spots & 100sf of storage area, don’t miss out on a home of this size in Maple Leaf!",
        "Price": "$1,049,950",
        "Media": "https://login.focusedmediacollective.com/8512-1st-Ave-NE",
        "Header": "/static/images/PropertyPhotos/8514_header.png",
    },
    {
        "Address": "8512 1st Ave NE",
        "Subaddress": "Seattle, WA 98115",
        "Photos": ["/static/images/PropertyPhotos/8512/A.jpg","/static/images/PropertyPhotos/8512/AA.jpg","/static/images/PropertyPhotos/8512/B.jpg","/static/images/PropertyPhotos/8512/C.jpg","/static/images/PropertyPhotos/8512/D.jpg","/static/images/PropertyPhotos/8512/E.jpg","/static/images/PropertyPhotos/8512/F.jpg","/static/images/PropertyPhotos/8512/G.jpg","/static/images/PropertyPhotos/8512/H.jpg","/static/images/PropertyPhotos/8512/I.jpg","/static/images/PropertyPhotos/8512/J.jpg","/static/images/PropertyPhotos/8512/K.jpg","/static/images/PropertyPhotos/8512/L.jpg","/static/images/PropertyPhotos/8512/M.jpg","/static/images/PropertyPhotos/8512/N.jpg",],
        "MLS": "2164529",
        "Beds": 2,
        "Baths": 1,
        "SqFt": "694 SqFt",
        "MarketingRemarks": "This updated and adorable Maple Leaf standalone home is a rare find at this price point. Featuring tasteful updates everywhere that you look - stylish flooring throughout, elegant stainless-steel appliances, and quartz countertops. Double paned windows allow for a quiet living experience with plenty of natural light. Freshly painted exterior along with a reimagined front yard combine for a new outdoor entertaining area to take advantage of. Come see for yourself! Fantastic location with Maple Leaf Reservoir Park, Green Lake and many outstanding restaurants and shops close by.",
        "Price": "$469,950",
        "Header": "/static/images/PropertyPhotos/8512_header.png",
    },
    {
        "Address": "758 & 760N 72nd St",
        "Subaddress": "Seattle, WA 98103",
        "Photos": ["/static/images/PropertyPhotos/758B/1.jpg",],
        "MLS": "2161927",
        "Beds": 2,
        "Baths": 1.75,
        "SqFt": "1,271-1,391 SqFt",
        "MarketingRemarks": "Ideally situated between the desirable neighborhoods of Green Lake and Phinney Ridge, prepare to be enchanted by the unobstructed views of Green Lake and the Cascade Mountains from your very own rooftop oasis. As you enter the home, you'll be welcomed by the premium hardwood flooring that seamlessly connects each room. Revel in the abundant natural light that bathes every nook, crafting an inviting and warm ambiance throughout. This home boasts the latest in contemporary design, including top-tier appliances and modern finishes that elevate every inch. Finally, take a moment to unwind on your private patio. Convenience is at your doorstep! Embrace the urban lifestyle with easy access to shops, restaurants, parks, and entertainment venues.",
        "Price": "$769,950-$829,950",
        "Media": "https://login.focusedmediacollective.com/758-N-72nd-St",
        "Header": "/static/images/PropertyPhotos/760A_header.png",

    },
    {
        "Address": "1805 N 105th St",
        "Subaddress": "Seattle, WA 98133",
        "Photos": ["/static/images/PropertyPhotos/1805/1.jpeg",],
        "MLS": "TBD",
        "Beds": 2,
        "Baths": 2.5,
        "SqFt": "1,050 SqFt",
        "MarketingRemarks": "Welcome to Parkside Cottages, where charm meets modern living! These newly constructed 2-bedroom, 2.5-bathroom homes are nestled in a walkable neighborhood overlooking scenic Mineral Park. When you step inside, you’ll discover an elegantly designed modern interior, complete with two spacious bedrooms, each boasting its own en-suite bathroom. The open concept living area seamlessly connects to a generous outdoor space, perfect for relaxing and entertaining. It won’t take long to see how these homes effortlessly blend convenience and comfort. Just a short stroll away a vibrant community beckons, offering an array of shops, dining options, entertainment, and easy access to the light rail. Don't miss your chance to own a piece of this walkable paradise – come experience it for yourself!",
        "Price": "Call for pricing",
        "Header": "/static/images/PropertyPhotos/1805_header.png",

    },

    {
        "Address": "1938 S Lander St",
        "Subaddress": "Seattle, WA 98144",
        "Photos": ["/static/images/PropertyPhotos/1938/1.jpg",],
        "MLS": "2141524",
        "Beds": 2,
        "Baths": 1.5,
        "SqFt": "919 SqFt",
        "MarketingRemarks": "This new construction free standing home features quartz countertops, stainless steel appliances, stylish backsplashes, and other high end finishes throughout. Vaulted ceilings, skylights, and strategically placed windows allow for the perfect combination of natural light, privacy, and views of the Cascade Mountains. The well designed kitchen and functional living room flows onto a private patio - ready for customization and backyard entertainment. Inside you’ll keep cool with the high efficiency A/C. Ideally located in the desirable neighborhood of Beacon Hill with plentiful top-rated restaurants, shops, and parks close by. With the Light Rail Station and other transit options only a 5 minute walk away, this location is a commuter's dream.",
        "Price": "$639,950",
        "Media": "https://login.focusedmediacollective.com/1938SLanderSt",
        "Header": "/static/images/PropertyPhotos/1938_header.png",

    }, 
    {
        "Address": "3008 12th Ave S #A",
        "Subaddress": "Seattle, WA",
        "Photos": ["/static/images/PropertyPhotos/3012/1.png",],
        "MLS": "TBD",
        "Beds": 3,
        "Baths": 2.25,
        "SqFt": "1590 SqFt",
        "MarketingRemarks": "Experience breathtaking views from your high-end new construction home in the most desirable spot on Beacon Hill. Spacious bedrooms, versatile lower floor for hosting or a private living space, combined with the impeccable craftsmanship of Rudd Development - make this the epitome of high-quality urban living. Discover the ultimate Seattle living experience with a modern design that blends seamlessly with the scenic beauty of the Pacific Northwest. Experience unparalleled luxury and serenity in this Seattle gem, offering breathtaking sunset views. With unobstructed roof-top views and walking proximity to Beacon Hill restaurants and retail, this home is unlike any other. Estimated completion date of November 22nd",
        "Price": "Call for pricing",
        "Header": "/static/images/PropertyPhotos/3012_header.png",

    },
    {
        "Address": "7557 15th Ave SW #C",
        "Subaddress": "Seattle, WA 98106",
        "Photos": ["/static/images/PropertyPhotos/7557/1.jpg",],
        "MLS": "2154618",
        "Beds": 2,
        "Baths": 1.5,
        "SqFt": "870 SqFt",
        "MarketingRemarks": "Experience the allure of this brand-new construction home, complete with convenient dedicated parking, an exclusive private patio, and an expansive yard. As you step inside, a warm and inviting living space seamlessly merges with a contemporary kitchen adorned with sleek quartz countertops, top-tier stainless steel appliances, and modern backsplash. The main floor hosts a stylish powder room and storage. Venture upstairs to discover two tranquil bedrooms and a luxurious four-piece bathroom, all bathed in an abundance of natural light that pours in through soaring ceilings. Situated in close proximity to the vibrant Alaska Junction, and a host of local amenities, this property offers the ideal fusion of modern living and urban convenience.",
        "Price": "$519,000",
        "Media": "https://login.focusedmediacollective.com/7557C15thAveSW",
        "Header": "/static/images/PropertyPhotos/7557_header.png",
    },
]

export default listings;
